FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG VUE_APP_API_BASE_URL=
ARG VUE_APP_OAUTH_SERVER_URL
ARG VUE_APP_OAUTH_CLIENT_ID
ARG VUE_APP_OAUTH_CLIENT_SECRET
ARG VUE_APP_OAUTH_REDIRECT_URI
ARG VUE_APP_OAUTH_SCOPE="read write"
ENV VUE_APP_API_BASE_URL=$VUE_APP_API_BASE_URL \
    VUE_APP_OAUTH_SERVER_URL=$VUE_APP_OAUTH_SERVER_URL \
    VUE_APP_OAUTH_CLIENT_ID=$VUE_APP_OAUTH_CLIENT_ID \
    VUE_APP_OAUTH_CLIENT_SECRET=$VUE_APP_OAUTH_CLIENT_SECRET \
    VUE_APP_OAUTH_REDIRECT_URI=$VUE_APP_OAUTH_REDIRECT_URI \
    VUE_APP_OAUTH_SCOPE=$VUE_APP_OAUTH_SCOPE
RUN npm run build

FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
